
name: MLKEM CI
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [ "main","safety_proofs"]
  pull_request:
    branches: ["main"]
    
env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  verification:
    name: Implementation Verification
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/implementation-checks.yml
    secrets: inherit 
  ec:
    name: EasyCrypt
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/ec.yml
    secrets: inherit 
  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
            submodules: recursive
      - uses: ./.github/actions/bench

